version: "2"

services:
 minetest:
  image: registry.gitlab.com/minetest/minetest/server:5.6.1
  restart: always
  user: root
  volumes:
   - "./data/world:/root/.minetest/worlds/world"
   - "./game:/root/.minetest/worlds/world/game"
   - "./worldmods:/root/.minetest/worlds/world/worldmods"
   - "./world.mt:/root/.minetest/worlds/world/world.mt"
   - "./minetest.conf:/minetest.conf"
  ports:
    - "30001:30001/udp"
  networks:
   - terminator
   - default
  entrypoint: ["minetestserver", "--config", "/minetest.conf"]

 matterbridge:
   image: 42wim/matterbridge:1.26.0
   dns:
    - 8.8.4.4
    - 8.8.8.8
   volumes:
    - ./matterbridge.toml:/etc/matterbridge/matterbridge.toml
    - ./remotenickformat.tengo:/remotenickformat.tengo

 mesecons-lab-ui:
  image: ghcr.io/minetest-go/mtui:1.27
  networks:
   - terminator
   - default
  environment:
   COOKIE_DOMAIN: "meseconslab.minetest.ch"
   COOKIE_SECURE: "true"
   WORLD_DIR: "/root/.minetest/worlds/world"
   API_KEY: "{{mtui_key}}"
   ENABLE_FEATURES: "shell,luashell,monitoring"
  volumes:
   - "./data/world:/root/.minetest/worlds/world"
   - "./world.mt:/root/.minetest/worlds/world/world.mt"
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.meseconslab.rule=Host(`meseconslab.minetest.ch`)"
    - "traefik.http.services.meseconslab.loadbalancer.server.port=8080"
    - "traefik.http.routers.meseconslab.entrypoints=websecure"
    - "traefik.http.routers.meseconslab.tls.certresolver=default"

networks:
 terminator:
  external: true
