version: "2"

services:
 minetest:
  image: registry.gitlab.com/minetest/minetest/server:5.6.1
  restart: always
  user: root
  volumes:
   - "./data/world:/root/.minetest/worlds/world"
   - "./game:/root/.minetest/worlds/world/game"
   - "./worldmods:/root/.minetest/worlds/world/worldmods"
   - "./world.mt:/root/.minetest/worlds/world/world.mt"
   - "./minetest.conf:/minetest.conf"
  ports:
    - "30001:30001/udp"
  networks:
   - terminator
  entrypoint: ["minetestserver", "--config", "/minetest.conf"]

 matterbridge:
   image: 42wim/matterbridge:1.25.2
   dns:
    - 8.8.4.4
    - 8.8.8.8
   volumes:
    - ./matterbridge.toml:/etc/matterbridge/matterbridge.toml

networks:
 terminator:
  external: true
